---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycrds.com.github.jw3
spec:
  group: com.github.jw3
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: mycrds
    singular: mycrd
    kind: MyCRD
  subresources:
    status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-operator
  template:
    metadata:
      labels:
        app: example-operator
    spec:
      containers:
        - name: operator
          image: jwiii/example-k8s-scala-operator:latest
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx128m"
            - name: CONFIG_MAP
              value: example-operator-config

          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-scala-operator
data:
  config: |
    example.operator {}
