---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gvcs.jw3.github.com
spec:
  group: jw3.github.com
  scope: Namespaced
  names:
    plural: gvcs
    singular: gvc
    kind: GVC
    shortNames:
      - gv
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uri:
                  type: string
                  pattern: '^http(s)?://.+?$'
                ref:
                  type: string
                  default: master
                pvsz:
                  type: string
                  default: 100Mi
                  pattern: '^\d+(M|G)i$'
      subresources:
        status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-operator
  template:
    metadata:
      labels:
        app: example-operator
    spec:
      containers:
        - name: operator
          image: jwiii/example-k8s-scala-operator:latest
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx128m"
            - name: CONFIG_MAP
              value: example-operator-config

          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-scala-operator
data:
  config: |
    example.operator {}
